# Generated by Django 6.0.4 on 2026-04-10 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enclosures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('size', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('species', models.CharField(max_length=500)),
                ('age', models.CharField(max_length=60)),
                ('health', models.CharField(max_length=100)),
                ('enclosure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.enclosures')),
            ],
        ),
    ]
